name: build web and preview
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      
      - name: "Web Build 🔧"
        run: |
          cd example/
          flutter pub get
          flutter build web --release --base-href="/flow_compose/"  --web-renderer html
      
      - name: "Web Deploy 🚀"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: ./example/build/web